version: '3.7'

services:
  web:
    build: ./abrmonitoring
    image: abrparsermanifest:1
    command: gunicorn abrmonitoring.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./abrmonitoring/:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - ./abrmonitoring/.env
