version: '3.7'

services:
  web:
    build: ./hlsparser
    image: hlsparser:1
    command: gunicorn hlsparser.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./hlsparser/:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - ./hlsparser/.env
