version: '3.7'

services:
  parser:
    build: ./hlsparser
    image: hlsparser:2
    container_name: hls_parser
    networks:
      - abrmonitor
    volumes:
      - ./hlsparser/:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - ./hlsparser/.env
 #chunk-chek:
 #  build: ./chunkcheck
 #  image: chunk-check:1
 #  command: tail -F /var/log/cron.log 
 #  container_name: chunk-check 
 #  networks:
 #    - abrmonitor
 #  env_file:
 #    - ./chunkcheck/.env

networks:
  abrmonitor:
