apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "2 workers"
  name: hlsk8s-deployment
  labels:
    app: hlsk8s 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hlsk8s
  template:
    metadata:
      labels:
        app: hlsk8s
    spec:
      hostname: hlsk8s
      subdomain: default-subdomain
      dnsPolicy: "None"
      dnsConfig:
       nameservers:
        - 8.8.8.8
      containers:
        - name: hlsk8s
          imagePullPolicy: Always
          image: giopez/hlsparser:7
          command: ['sh', "-c", "gunicorn hlsparser.wsgi:application -w 14 --max-requests 1200 --timeout 10 --bind 0.0.0.0:8000"]
          env:
            - name: DEBUG
              value: "0"
            - name: SECRET_KEY
              value: "abrmonitoring"
            - name: DJANGO_ALLOWED_HOSTS
              value: "* hls_parser"
          ports:
          - containerPort: 8000
        - name: chunkcheck
          # imagePullPolicy: Always
          image: giopez/chunkcheck:0.0.1-6
          command: ['crond', '-l', '2', '-f']
          env:
            - name: V_PROFILE
              value: "5"
            - name: NUM_CHUNKS_TOB_CHECK
              value: "10"
            - name: RANDOM_PROFILES
              value: "0"
            - name: ASSET_LIST
              value: "./asset_list.yaml"
            - name: ABR_MANIFEST_SERVER_IP
              value: "localhost"
            - name: ABR_MANIFEST_SERVER_PORT
              value: "8000"
          ports:
          - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: hlsk8s-service
  labels:
    app: hlsk8s
spec:
  externalIPs:
  - 172.26.194.211
  type: NodePort
  selector:
    app: hlsk8s
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
      nodePort: 30000